# -*- coding: utf-8 -*-
"""Ep Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Hb9FAR0HZUrgcdos2nkFIyBL2xb3Cqz
"""

import pandas as pd
import numpy as np
from datetime import datetime

CO2_data=pd.read_csv('/content/CO2_Timeline_Detailed (1).csv')

CO2_data.columns

comb_engdata = pd.read_csv('/content/Combined_Average_Engine_Analysis.csv')

comb_engdata.columns

import matplotlib.pyplot as plt

plt.hist(comb_engdata['avg_torque'])
plt.show()

comb_engdata['datetime']

port_side= pd.read_csv('/content/Fuel_Analysis_Port.csv')

from datetime import datetime
port_side['datetime'] = pd.to_datetime(port_side['time'],unit="s", utc=False)

port_side.head(10)

trips_data=pd.read_excel('/content/all_navigation_trips1 (1).xlsx')

trips_data["date_dt"] =pd.to_datetime(trips_data["date"])
trips_data["starttime_td"] = trips_data["start_time"].apply(lambda t: pd.Timedelta(hours=t.hour, minutes=t.minute, seconds=t.second))
trips_data["start_datetime"] = trips_data["date_dt"] + trips_data["starttime_td"]
trips_data["endtime_td"] = trips_data["end_time"].apply(lambda t: pd.Timedelta(hours=t.hour, minutes=t.minute, seconds=t.second))
trips_data["end_datetime"] = trips_data["date_dt"] + trips_data["endtime_td"]

trips_data.head()

trips_data = trips_data.drop(columns=['date','trip_id','start_time','end_time','is_real_trip','date_dt','starttime_td','endtime_td'])

trips_data.head()

trips_data = trips_data.drop(columns=['endtime_td'])

trips_data

port_side['datetime'] = pd.to_datetime(port_side['time'],unit="s", utc=False)

port_side.head(5)

def calculate_tripEnerrgy(df1,df2,column_name):
  for i in range(len(df2)):
    start_time=df2['start_datetime'][i]
    end_time=df2['end_datetime'][i]
    mask = (df1["datetime"] >= start_time) & (df1["datetime"] <= end_time)
    df_filtered = df1.loc[mask]
    df_filtered["delta_t"] = df_filtered["datetime"].diff().dt.total_seconds()
    df_filtered["delta_t"].fillna(0, inplace=True)
    df_filtered['Energy(J)']=df_filtered['power_kw']*df_filtered['delta_t']*1000
    df2.loc[i,column_name]=df_filtered['Energy(J)'].sum()
  return df2

calculate_tripEnerrgy(port_side,trips_data,'Energy_port')

plt.hist(trips_data['trip_Energy'], bins=25)
plt.show()

stbd_side=pd.read_csv('/content/Fuel_Analysis_Starboard (1).csv')
stbd_side['datetime'] = pd.to_datetime(stbd_side['time'],unit="s", utc=False)

trips_data['total_Energy(kWh)']=(trips_data['Energy_Starboard']+trips_data['Energy_port'])/(3.6*(10**6))

trips_data

plt.hist(trips_data['total_Energy(kWh)'], bins=25)
plt.show()

from google.colab import files
trips_data.to_csv('trips_data.csv', index=False)
files.download('trips_data.csv')

trips_data['total_Energy(kWh)'].max()

def fuel_consumption(start_time, end_time, data):
  mask = (data["datetime"] >= start_time) & (data["datetime"] <= end_time)
  date_data = data.loc[mask]
  date_data["delta_t"] = date_data["datetime"].diff().dt.total_seconds()
  date_data["delta_t"].fillna(0, inplace=True)
  date_data['Fuel_Consumed(l)']=date_data['fuel_lph']*(date_data['delta_t']/3600)
  Total_fuel_consumed = date_data['Fuel_Consumed(l)'].sum()
  fuel_consumed_data=pd.DataFrame(columns=["start_time", "end_time",'tot_fuel_consumed(l)'])
  new_row = pd.DataFrame([{"start_time": start_time,"end_time": end_time, "tot_fuel-consumed(l)": Total_fuel_consumed}])
  fuel_consumed_data = pd.concat([fuel_consumed_data, new_row], ignore_index=True)

  return fuel_consumed_data

engine_data=pd.read_csv('/content/engine_data_complete.csv')
plt.hist(engine_data['rpm'], bins=250)
plt.show()

def extract_day(start_time, end_time, data):
  mask = (data["datetime"] >= start_time) & (data["datetime"] <= end_time)
  day_data = data.loc[mask]
  return day_data

#startboard data
starttime_1=pd.Timestamp("2025-06-08 00:00:00")
endttime_1=pd.Timestamp("2025-06-08 23:59:59")

starttime_2=pd.Timestamp("2025-06-09 00:00:00")
endttime_2=pd.Timestamp("2025-06-09 23:59:59")

starttime_3=pd.Timestamp("2025-06-10 00:00:00")
endttime_3=pd.Timestamp("2025-06-10 23:59:59")

starttime_4=pd.Timestamp("2025-06-11 00:00:00")
endttime_4=pd.Timestamp("2025-06-11 23:59:59")

starttime_5=pd.Timestamp("2025-06-12 00:00:00")
endttime_5=pd.Timestamp("2025-06-12 23:59:59")

starttime_6=pd.Timestamp("2025-06-13 00:00:00")
endttime_6=pd.Timestamp("2025-06-13 23:59:59")

starttime_7=pd.Timestamp("2025-06-14 00:00:00")
endttime_7=pd.Timestamp("2025-06-14 23:59:59")

starttime_8=pd.Timestamp("2025-06-15 00:00:00")
endttime_8=pd.Timestamp("2025-06-15 23:59:59")

starttime_9=pd.Timestamp("2025-06-16 00:00:00")
endttime_9=pd.Timestamp("2025-06-16 23:59:59")

day_1port=extract_day(starttime_1, endttime_1,port_side)
day_2port=extract_day(starttime_2, endttime_2,port_side)
day_3port=extract_day(starttime_3, endttime_3,port_side)
day_4port=extract_day(starttime_4, endttime_4,port_side)
day_5port=extract_day(starttime_5, endttime_5,port_side)
day_6port=extract_day(starttime_6, endttime_6,port_side)
day_7port=extract_day(starttime_7, endttime_7,port_side)
day_8port=extract_day(starttime_8, endttime_8,port_side)
day_9port=extract_day(starttime_9, endttime_9,port_side)

day_1stbd=extract_day(starttime_1, endttime_1,stbd_side)
day_2stbd=extract_day(starttime_2, endttime_2,stbd_side)
day_3stbd=extract_day(starttime_3, endttime_3,stbd_side)
day_4stbd=extract_day(starttime_4, endttime_4,stbd_side)
day_5stbd=extract_day(starttime_5, endttime_5,stbd_side)
day_6stbd=extract_day(starttime_6, endttime_6,stbd_side)
day_7stbd=extract_day(starttime_7, endttime_7,stbd_side)
day_8stbd=extract_day(starttime_8, endttime_8,stbd_side)
day_9stbd=extract_day(starttime_9, endttime_9,stbd_side)

from google.colab import files
day_9port.to_csv('day_9port', index=False)
files.download('day_9port')

from google.colab import files
day_9stbd.to_csv('day_9stbd', index=False)
files.download('day_9stbd')



def create_daily_data(start_time, end_time, data):
  mask = (data["datetime"] >= start_time) & (data["datetime"] <= end_time)
  day_data = data.loc[mask]
  day_data["delta_t"] = day_data["datetime"].diff().dt.total_seconds()
  day_data["delta_t"].fillna(0, inplace=True)
  day_data['Energy(J)']=day_data['power_kw']*day_data['delta_t']*1000
  day_data['Fuel_Consumed(l)']=day_data['fuel_lph']*(day_data['delta_t']/3600)
  return day_data

#startboard data
starttime_1=pd.Timestamp("2025-06-08 00:00:00")
endttime_1=pd.Timestamp("2025-06-08 23:59:59")

starttime_2=pd.Timestamp("2025-06-09 00:00:00")
endttime_2=pd.Timestamp("2025-06-09 23:59:59")

starttime_3=pd.Timestamp("2025-06-10 00:00:00")
endttime_3=pd.Timestamp("2025-06-10 23:59:59")

starttime_4=pd.Timestamp("2025-06-11 00:00:00")
endttime_4=pd.Timestamp("2025-06-11 23:59:59")

starttime_5=pd.Timestamp("2025-06-12 00:00:00")
endttime_5=pd.Timestamp("2025-06-12 23:59:59")

starttime_6=pd.Timestamp("2025-06-13 00:00:00")
endttime_6=pd.Timestamp("2025-06-13 23:59:59")

starttime_7=pd.Timestamp("2025-06-14 00:00:00")
endttime_7=pd.Timestamp("2025-06-14 23:59:59")

starttime_8=pd.Timestamp("2025-06-15 00:00:00")
endttime_8=pd.Timestamp("2025-06-15 23:59:59")

starttime_9=pd.Timestamp("2025-06-16 00:00:00")
endttime_9=pd.Timestamp("2025-06-16 23:59:59")

day_1p=create_daily_data(starttime_1, endttime_1,port_side)
day_2p=create_daily_data(starttime_2, endttime_2,port_side)
day_3p=create_daily_data(starttime_3, endttime_3,port_side)
day_4p=create_daily_data(starttime_4, endttime_4,port_side)
day_5p=create_daily_data(starttime_5, endttime_5,port_side)
day_6p=create_daily_data(starttime_6, endttime_6,port_side)
day_7p=create_daily_data(starttime_7, endttime_7,port_side)
day_8p=create_daily_data(starttime_8, endttime_8,port_side)
day_9p=create_daily_data(starttime_9, endttime_9,port_side)

def create_sizing_summary(index, day):
    fuel_ = day['Fuel_Consumed(l)'].sum()
    energy_ = day['Energy(J)'].sum() / 1000  # convert to kJ
    return {"day": index, "fuel_(l)": fuel_, "energy_(KJ)": energy_}

days=(day_1,day_2,day_3,day_4,day_5,day_6,day_7,day_8,day_9)


# Build a list of dicts first
summary_list = []

for i, day in enumerate(days, start=1):  # i = 1, 2, ..., 9
    summary_list.append(create_sizing_summary(i, day))

# Convert list of dicts to DataFrame once
data_sheet_port = pd.DataFrame(summary_list)
print(data_sheet_port)

Starboard_1=create_daily_data(starttime_1, endttime_1,starboard_side)
Starboard_2=create_daily_data(starttime_2, endttime_2,starboard_side)
Starboard_3=create_daily_data(starttime_3, endttime_3,starboard_side)
Starboard_4=create_daily_data(starttime_4, endttime_4,starboard_side)
Starboard_5=create_daily_data(starttime_5, endttime_5,starboard_side)
Starboard_6=create_daily_data(starttime_6, endttime_6,starboard_side)
Starboard_7=create_daily_data(starttime_7, endttime_7,starboard_side)
Starboard_8=create_daily_data(starttime_8, endttime_8,starboard_side)
Starboard_9=create_daily_data(starttime_9, endttime_9,starboard_side)

Starboard_1

Starboard_days=(Starboard_1,Starboard_2,Starboard_3,Starboard_4,Starboard_5,Starboard_6,Starboard_7,Starboard_8,Starboard_9)
# Build a list of dicts first
summary_list_starboard = []

for i, s_day in enumerate(Starboard_days, start=1):  # i = 1, 2, ..., 9
    summary_list_starboard.append(create_sizing_summary(i, s_day))

# Convert list of dicts to DataFrame once
data_sheet_stbd = pd.DataFrame(summary_list_starboard)
print(data_sheet_stbd)

combined_consumption = pd.DataFrame(columns=["day", "tot_fuel(l)", "tot_Energy(KJ)"])

# Copy day column from one of the DataFrames
combined_consumption['day'] = data_sheet_port['day']

combined_consumption['tot_fuel(l)'] = data_sheet_port['fuel_(l)'] + data_sheet_stbd['fuel_(l)']
combined_consumption['tot_Energy(KJ)'] = data_sheet_port['energy_(KJ)'] + data_sheet_stbd['energy_(KJ)']

print(combined_consumption)



from google.colab import files
combined_consumption.to_csv('combined_consumption.csv', index=False)
files.download('combined_consumption.csv')